language: java
jdk:
- oraclejdk8
script: mvn package
deploy:
  provider: s3
  access_key_id: AKIAI6HJS7WUWNPCMVBQ
  secret_access_key:
    secure: UvUrCnsLnp20DQ8gnvFdG2hwT2/bAoth0Kw4SERBh8xfI3B1pR2havlma1HXEW/oroSBn37xfEi4Lq87kC8qOjDAmpRx77U+KIma1RH0pqsyOsu4qLn8ZoKeyedpKfS7lrmKhCr2qX0RGnWTTRhb+gJDdOqnla6GO5Z5+2JUsP84/rt73d9eCrn+IBd14+LdO1TL3d6OqTr1dS2ZiDDvd63JtaCOCLie8APaDHDZJ+MBjgyCqBZOgRQr/IHzDSzKVTu6RiPHvYM4GOassX+QKY++Vej02WBrZrWLYa2bEM0QfQ3f00YGLEKaQEUWUW2KV71Zpl7wP9Myh9xffeKKdpEZ7m/wKPU8wB5QXIMuFOsjaoO2cjZjHefc7Lad/OMDf1ge32jN7f0PdJ7aeyw43A1KlLWeLBDDEyu2cO+s55ouZdwHzBp6zYrVhjhAUKBmRG9wYoPkoE9n/DbcNX2SWv27hI8NlqMg5+ePv9hi+LwZUfM9mK9If1u46uH4MHztIyKwJqQM8FXt7CIt0bC0oDXaNuSqZqG3L7zoVwwDsbYVGFEZgKAztkUM3uHYESBHprBqlMBj9A80HWAHFqwOn8CTW0H+9SPu1CGAxiYTBKv22ZjCC1wx/WFSsrDaFiePJZBJWNVB9X9fxcgYoKcldr4FC1/6DlMm2QG5B9KspuI=
  bucket: digitalmarketplacealerter.cgi-digital.uk
  skip_cleanup: true
  acl: public_read
  region: eu-west-1

